### ISSUE TITLE
Review by tenntenn

### ISSUE THREAD

**Issue by tenntenn** [micnncim/bitbrew#7]
- 全体的にクォリティ高い
- READMEがしっかりしてる

- [x] 自作とサードパーティを分ける流派？
https://github.com/micnncim/bitbrew/blob/master/cli/cli.go#L5

- [x] ゼロ値でよい
```go
var eg errgroup.Group
```
https://github.com/micnncim/bitbrew/blob/master/bitbrew/bitbrew.go#L123

- [x] 一気にメモリ上に乗せても大丈夫なやつ？
https://github.com/micnncim/bitbrew/blob/master/bitbrew/bitbrew.go#L133

- [ ] 埋め込みを用いる必要性はあるのか？
https://github.com/micnncim/bitbrew/blob/master/bitbrew/client.go#L25

- [x] 不要なコメントは消す
デバッグ用であればコメントを書く
https://github.com/micnncim/bitbrew/blob/master/github/github.go#L28

- [x] テストヘルパーなので`t.Helper`を呼ぶ
他のヘルパーについても同様
https://github.com/micnncim/bitbrew/blob/master/internal/testutil/testutil.go#L13

- [x] `os.IsExist`しなくていい？
https://golang.org/pkg/os/#IsExist
https://github.com/micnncim/bitbrew/blob/master/internal/testutil/testutil.go#L70

**Comment by micnncim** [comment]
レビューありがとうございます！
直します！

> 自作とサードパーティを分ける流派？

GoLand の `goimports` のオプションであるので使っています
